# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Местоположение', 'verbose_name_plural': 'Местоположение'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контактные данные', 'verbose_name_plural': 'Контактные данные'},
        ),
    ]
