# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
